name: get_template
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #国际化
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  #网络请求
  dio: 5.0.0
  dio_cookie_manager: 2.1.0
  dio_cache_interceptor: ^3.2.7
  dio_cache_interceptor_hive_store: ^3.2.0
  # 数据存储
  shared_preferences: ^2.0.17
  # 图片加载
  cached_network_image: ^3.2.3
  # json序列化
  freezed_annotation: ^2.0.3
  # 屏幕适配
  flutter_screenutil: ^5.6.1
  # 框架
  get: ^4.6.5
  # 国际化
  intl: ^0.17.0
  # 日志
  logging: ^1.1.1
  # web_view
  webview_flutter: ^4.0.2
  # 权限管理
  permission_handler: ^10.2.0
  path_provider: ^2.0.12
  # 轮播图
  carousel_slider: ^4.2.1
  # 吐司
  oktoast: ^3.3.1
  # 元组
  tuple: ^2.0.1
  path: ^1.8.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  freezed: ^2.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.3.0
  json_serializable: ^6.1.3
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_gen:
  output: lib/gen/
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: false
      class_name: Assets

